### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by IceCubeDev** [IceCubeDev/CodeSnippets-Projects#1]
There is a problem in the thread server written in Python. Something is causing the test from Apache ab to fail with the error "arp_socket_recv: Connection reset by peer (104)" resulting in failure of the test and an exception to be thrown on the server. This is probably due to the premature closing of a socket by the server. Even if the server is not closing the sockets, we still get the same error.

    Exception in thread Thread-6:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
        self.run()
      File "WebServer/web/threaded/WorkerThread.py", line 65, in run
        handler.socket.shutdown(socket.SHUT_RDWR)
    OSError: [Errno 107] Transport endpoint is not connected

**Comment by IceCubeDev** [comment]
Bug was fixed. The Linux kernel was terminating all connections to the server, because I though the server was doing a SYN Flood attack.
